### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by darren-stoll** [baldnate/src-pbs-to-csv#3]
```
D:\Downloads\src-pbs-to-csv-main\src-pbs-to-csv-main>python src-pbs-to-csv.py doicm output.csv
Traceback (most recent call last):
  File "D:\Downloads\src-pbs-to-csv-main\src-pbs-to-csv-main\src-pbs-to-csv.py", line 102, in <module>
    runsdf['video'] = rawdf.apply(lambda x: getVideo(x['videos']), axis=1)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 8740, in apply
    return op.apply()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\apply.py", line 688, in apply
    return self.apply_standard()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "D:\Downloads\src-pbs-to-csv-main\src-pbs-to-csv-main\src-pbs-to-csv.py", line 102, in <lambda>
    runsdf['video'] = rawdf.apply(lambda x: getVideo(x['videos']), axis=1)
  File "D:\Downloads\src-pbs-to-csv-main\src-pbs-to-csv-main\src-pbs-to-csv.py", line 75, in getVideo
    if 'links' in x and len(x['links']) > 0:
TypeError: argument of type 'NoneType' is not iterable
```

I'm guessing that if no video is attached to the record, then the pull fails?

**Comment by baldnate** [comment]
Fixed, thanks for the report.
