### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Kinnin11** [baldnate/src-pbs-to-csv#5]
```
Traceback (most recent call last):
  File "src-pbs-to-csv.py", line 131, in <module>
    runsdf['video'] = rawdf.apply(lambda x: getVideo(x['videos']), axis=1)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\frame.py", line 8740, in apply
    return op.apply()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\apply.py", line 688, in apply
    return self.apply_standard()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "src-pbs-to-csv.py", line 131, in <lambda>
    runsdf['video'] = rawdf.apply(lambda x: getVideo(x['videos']), axis=1)
  File "src-pbs-to-csv.py", line 104, in getVideo
    vids = [y['uri'] for y in x['links']]
TypeError: 'NoneType' object is not subscriptable
```
Seems very similar to an earlier issue, but it seems to be a different thing going wrong?

**Comment by baldnate** [comment]
Fixed, thanks for the report!
